name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56fb555a413c5bd5a9c6c67a1adb88838a7bf5763941fe3abb9ceafa2995f751"

[versions]
fabric = "0.18.5"
minecraft = "1.20.4"
