name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b09ef69816677d5fdd9fe989c1e6882b708d1d10d0c8a25464c4f01e4c8ee655"

[versions]
fabric = "0.18.5"
minecraft = "1.20.4"
