name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c8b9964b97335843ab66f9937de10ed265d63df15a71c875daaa85615e951d3"

[versions]
fabric = "0.18.5"
minecraft = "1.16.5"
