name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c3087ee22e5c32a939f50cccdf5eed3a796f656ce26e38f457d29775febb9b6"

[versions]
fabric = "0.18.5"
minecraft = "1.16.5"
