name = "Additive"
author = "SkywardMC"
version = "26.1.1+mc26.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac5f16a47376f96087b32cbc7d5528c3be6f41c556a2923938940da4ceb19a66"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-snapshot-1", "26.1-snapshot-2", "26.1-snapshot-3", "26.1-snapshot-4", "26.1-snapshot-5", "26.1-snapshot-6", "26.1-snapshot-7", "26.1-snapshot-8", "26.1-snapshot-9", "26.1-snapshot-10", "26.1-snapshot-11", "26.1-pre-1", "26.1-pre-2", "26.1-pre-3", "26.1-rc-1", "26.1-rc-2", "26.1-rc-3", "26.1"]
