name = "Additive"
author = "SkywardMC"
version = "26.4.0+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eee002c9bb5eedf6f8a3ae0035a09b3ec1c1e4f014b6e1a87cb569573ff5640"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
