name = "Additive"
author = "SkywardMC"
version = "26.4.0+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09127ca97b4fdcffc9598fc84cf4f4fb52ef7fbd0b8190d8cfa76be0ca269301"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
