name = "Additive"
author = "SkywardMC"
version = "26.1.4+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "075b9cdb261decbb6ca790e13ba5b38e109d1df6dc8746a1b8c38c0289d59a20"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
