name = "Additive"
author = "SkywardMC"
version = "1.44.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c09b8266ce797dfde590099cbb3a06156ed16dd551d3f47dd0d5981b34690a34"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
