name = "Additive"
author = "SkywardMC"
version = "26.2.0+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "830801bfe8ffb7e303dcadd4149f895286bc557ceb507d6d527b7e0f8ecfa1cc"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
