name = "Additive"
author = "SkywardMC"
version = "26.2.0+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ec55b3894add547c1d5666eb4da5a8dffeaa1ad4717c1eb212e419eda048306"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
