name = "Additive"
author = "SkywardMC"
version = "26.3.0+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "937e0a915bbef31294e90db723313aa87450ab162ed852f2d99a29dd30953dfe"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
