name = "Additive"
author = "SkywardMC"
version = "26.1.4+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f202267184db4c7e48ba8f6081cf576aebf0a8ff2ad0734b95268bd0080833c"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
