name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccbdafebb88f662919d1f966b7c1de1bb5551d4518d971d6c3c4a0caea047c2e"

[versions]
fabric = "0.18.5"
minecraft = "1.19.2"
