name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a40c85a604b1a755e6e843f1ff17053a30e81158f3ad6986397c1fcbfddc6b62"

[versions]
fabric = "0.18.4"
minecraft = "1.19.2"
