name = "Additive"
author = "SkywardMC"
version = "1.44.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6ae637fe9c8fa38cc3b70a1321d7a349a6cc681634ddd12cd694c3c5d851a17"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
