name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96de3e210b77ab8e2b5049ada5d309fa7fe225b8b073107ff2d6d8408b597a60"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
