name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7807320dd87160af3e07c68e8cadd99676797296ad352fe1c237945d6da8abe"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
