name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "683aaabf32155387cc1526fd25786e0d64a5992565c2daff9de25f544063672d"

[versions]
fabric = "0.18.5"
minecraft = "1.18.2"
