[general]
help_link = "https://discord.gg/36Tv44cYte"
formulation_type = "DISCORD"
upload_to = "mclo.gs"

[text]
support_name = "SkywardMC Discord"
support_place = "#support channel"
modpack_name = "Additive"

[modpack_modlist]
enabled = false

[piracy]
enabled = true
delay = 0

[greeting]
shown_greeting = true

[scripts]
enabled = false
