name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa5843d6c8297bbaa4ff76c12fe1764445f0cef5e3ad8d41aa7a30109b35f361"

[versions]
fabric = "0.18.5"
minecraft = "1.19.4"
