name = "Additive"
author = "SkywardMC"
version = "26.3.1+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5f257de491301f1709569ee2da3e35aa3149a78a2ff668dcbd4554d0a64d174"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
