name = "Additive"
author = "SkywardMC"
version = "26.1+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4396139108aeb1a4ba81bdd1e4ef67ff0e5b40dfecc5a3774b31e75a64f60ba"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
