name = "Additive"
author = "SkywardMC"
version = "26.4.1+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d60e24d7b2f1e25ad3f7c7aff34e7908f11610d209bc3366c824c13d69c61f4"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
