name = "Additive"
author = "SkywardMC"
version = "26.5.1+mc26.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3459e0141d79e60cd9b42e9cb08284838019b16f4fb82775a889e0d5521c6732"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
no-internal-hashes = true
