name = "Additive"
author = "SkywardMC"
version = "26.4.3+mc26.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
acceptable-game-versions = ["26.3-snapshot-1", "26.3-snapshot-2", "26.3-snapshot-3", "26.3-snapshot-4", "26.3-snapshot-5", "26.3-snapshot-6", "26.3-snapshot-7", "26.3-snapshot-8", "26.3-snapshot-9", "26.3-snapshot-10", "26.3-pre-1", "26.3-pre-2", "26.3-pre-3", "26.3-rc-1", "26.3-rc-2", "26.3-rc-3", "26.3"]
no-internal-hashes = true
